### ISSUE TITLE
3/19/15 - Autumn To Do

### ISSUE THREAD

**Issue by JonathanJansma** [WITBEntertainment/HarmonyOfDawn#92]
Autumn:
Make Water Mat Brighter
Make a list of things you need the pen for - Done
re-3d model hair for Helena - Done
General Model Edits - Done
Give Jon Seed Model - Done
Helena Clothing Edits - Done
Simplify material organization
Adjust Helena material for POST - Done
Helena Clothing Mat Edits for Post

**Comment by AtomPotato** [comment]
Pen Needs:

Seed Texture
Helena body Texture
Helena Hair texture
Helena Cloth texture
Pixie cloth texture
Pixie texture
